# Generated by Django 3.1.5 on 2021-01-22 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pizzaloversproject.back.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzalover',
            name='numberOfVotes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(validators=[pizzaloversproject.back.models.validate_message_content])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
