# Generated by Django 3.1.5 on 2021-01-23 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_auto_20210122_2058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventMsg',
        ),
    ]
